services:

  client:

    build: 
      context: ./client
      target: development

    ports:
      - "8080:5173"
    
    volumes:
      - ./client:/app
      - /app/node_modules
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLIN: true
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - server

  server:

    build: ./server

    ports:
      - "3000:3000"

    volumes:
      - ./server:/app
      - /app/node_modules
    
    env_file:
      - .env
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      MYSQL_SERVER: db
      TZ: ${TZ}
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - db
  
  db:

    image: mysql:latest

    env_file:
      - .env

    ports:
      - "3306:3306"

    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
      
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
