services:

  client:

    build: 
      context: .
      dockerfile: ./client/Dockerfile
      target: development

    ports:
      - "8080:5173"
    
    volumes:
      - ./client:/app/client
      # - ./packages/shared-schema:/app/packages/shared-schema
      - /app/client/node_modules
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLIN: true
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - server

  server:

    build: 
      context: .
      dockerfile: ./server/Dockerfile

    ports:
      - "3000:3000"
      - "5555:5555"

    volumes:
      - ./server:/app/server
      # - ./packages/shared-schema:/app/packages/shared-schema
      - /app/server/node_modules
    
    env_file:
      - .env
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      MYSQL_SERVER: db
      TZ: ${TZ}
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - db
  
  db:

    image: mysql:9.3

    env_file:
      - .env

    ports:
      - "3306:3306"

    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
      
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
