services:

  frontend:

    extends:
      file: ../../shared/compose.common-services.yml
      service: webapp

    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development

    ports:
      - "8080:5173"

    volumes:
      - ./frontend:/app/frontend
      # - ./packages/shared-schema:/app/packages/shared-schema
      - /app/frontend/node_modules

    environment:
      NODE_ENV: development

    depends_on:
      - backend

  backend:

    extends:
      file: ../../shared/compose.common-services.yml
      service: webapp

    build: 
      context: .
      dockerfile: ./backend/Dockerfile

    ports:
      - "3000:3000"
      - "5555:5555"

    volumes:
      - ./backend:/app/backend
      # - ./packages/shared-schema:/app/packages/shared-schema
      
      - /app/backend/node_modules

    environment:
      NODE_ENV: development
      MYSQL_SERVER: db

    depends_on:
      - db
  
  db:

    extends:
      file: ../../shared/compose.common-services.yml
      service: mysql

networks:
  app-network:

volumes:
  db-data:
    name: webapp-todo-db
