services:
    frontend:
        extends:
            file: ../../shared/compose.common-services.yml
            service: webapp

        build:
            context: .
            dockerfile: ./Dockerfile.frontend
            target: development

        ports:
            - "8080:5173"

        volumes:
            - ./frontend:/app/frontend
            - ./shared:/app/shared
            - /app/node_modules
            - /app/frontend/node_modules
            - /app/shared/node_modules

        environment:
            NODE_ENV: development

        depends_on:
            - backend

    backend:
        extends:
            file: ../../shared/compose.common-services.yml
            service: webapp

        build:
            context: .
            dockerfile: ./Dockerfile.backend
            target: development

        ports:
            - "3000:3000"
            - "5555:5555"

        volumes:
            - ./backend:/app/backend
            - ./shared:/app/shared
            - /app/node_modules
            - /app/backend/node_modules
            - /app/shared/node_modules

        environment:
            NODE_ENV: development
            MYSQL_SERVER: db
            CORS_ORIGIN: http://localhost:8080

        depends_on:
            - db

    db:
        extends:
            file: ../../shared/compose.common-services.yml
            service: postgres

networks:
    app-network:

volumes:
    db-data:
        name: webapp-todo-db
