FROM node:25-alpine AS base

WORKDIR /app

COPY ./shared ./shared
COPY package*.json .
COPY backend/package.json ./backend/

RUN npm install

COPY ./backend ./backend

WORKDIR /app/backend

FROM base AS development
CMD ["npm", "run", "dev"]

FROM base AS builder
RUN npm run build

FROM node:25-alpine AS deployment

WORKDIR /app

COPY --from=builder /app/backend/prisma.config.ts .
COPY --from=builder /app/backend/prisma/schema.prisma ./prisma/

COPY --from=builder /app/package*.json .
COPY --from=builder /app/backend/dist ./
COPY --from=builder /app/backend/package.json ./backend/
COPY --from=builder /app/shared/package.json ./shared/

RUN npm install --omit=dev

EXPOSE 3000

CMD ["node", "backend/src/app.js"]
