FROM node:25-alpine AS base

WORKDIR /app

COPY ./shared ./shared
COPY package*.json .
COPY backend/package.json ./backend/

RUN npm install

COPY ./backend ./backend

WORKDIR /app/backend

FROM base AS development
CMD ["npm", "run", "dev"]

FROM base AS builder
RUN npm run build

FROM node:25-alpine AS deployment

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

COPY --from=builder /app/backend/package.json ./backend/
COPY --from=builder /app/backend/dist ./backend/dist

COPY --from=builder /app/shared/package.json ./shared/
COPY --from=builder /app/shared/dist ./shared/dist

EXPOSE 3000

WORKDIR /app/backend
CMD ["node", "dist/app.js"]
