FROM node:25-alpine AS base

WORKDIR /app

COPY shared ./shared
COPY package*.json .
COPY frontend/package.json frontend/

RUN npm install

COPY frontend ./frontend

WORKDIR /app/frontend

FROM base AS development
CMD ["npm", "run", "dev"]

FROM base AS builder
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

FROM nginx:alpine AS deployment
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
