services:

  frontend:

    extends:
      file: ../../shared/compose.common-services.yml
      service: webapp

    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: development

    ports:
      - "8080:5173"
    
    volumes:
      - ./src:/app/src
      - /app/node_modules

    environment:
      NODE_ENV: development

    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:

    extends:
      context: .
      file: ../../shared/compose.common-services.yml
      service: webapp

    build:
      dockerfile: ./docker/backend/Dockerfile
      target: backend-php-alpine

    ports:
      - "9000:9000"

    volumes:
      - ./src:/var/www/html/src
      - /var/www/html/vendor

    depends_on:
      - db
  
  db:

    extends:
      file: ../../shared/compose.common-services.yml
      service: mysql

networks:
  app-network:

volumes:
  db-data:
    name: webapp-todo-db
