services:

  frontend:

    build: 
      context: ./frontend
      target: development

    ports:
      - "5173:5173"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLIN: true
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - backend

  backend:

    build: 
      context: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      
    tty: true
      
    networks:
      - app-network

    depends_on:
      - db
  
  db:

    build: 
      context: ../../shared/db/mysql

    env_file:
      - ../../shared/db/mysql/.env

    ports:
      - "3306:3306"

    volumes:
      - db-data:/var/lib/mysql
      
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
    name: webapp-todo-db
