name: Manual Build & Deploy to Render

on:
    # 重要な変更点: workflow_dispatchトリガーを追加
    workflow_dispatch:
        inputs:
            branch_name:
                description: "Target branch to build and deploy from"
                required: true
                default: "main-react-nodejs"
                type: choice
                options:
                    - main-react-nodejs
            # 必要に応じて環境（ステージング、本番など）を選択できるようにすることもできます
            # environment:
            #   description: 'Deployment Environment'
            #   required: true
            #   default: 'production'
            #   type: environment

# ワークフロー内で使う変数をinputsから取得
env:
    REGISTRY: ghcr.io
    TARGET_BRANCH: ${{ github.event.inputs.branch_name }}
    TARGET_FOLDER: "stacks/react-nodejs" # フォルダ名とブランチ名の対応をここで定義
    # REPOSITORY: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            packages: write

        steps:
            # 1. 指定されたブランチのコードをチェックアウト
            - name: Checkout code from ${{ env.TARGET_BRANCH }}
              uses: actions/checkout@v4
              with:
                  ref: ${{ env.TARGET_BRANCH }} # 手動入力されたブランチを参照

            # 2. Dockerイメージのビルドとプッシュ
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # バックエンドイメージのビルドとプッシュ
            - name: Build and Push Backend Image
              uses: docker/build-push-action@v5
              with:
                  context: ./${{ env.TARGET_FOLDER }}
                  file: ./${{ env.TARGET_FOLDER }}/Dockerfile.backend
                  push: true
                  target: deployment
                  build-args: |
                      VITE_API_URL=${{ secrets.VITE_API_PROD_URL }}
                  tags: ${{ env.REGISTRY }}/rotterykrn/1day-todo/backend:latest

    deployment:
        runs-on: ubuntu-latest
        needs: build-and-push # ビルドとプッシュが完了してから実行

        steps:
            # --- バックエンド Web Service のデプロイをトリガー ---
            - name: Render Web Service (Backend) の再デプロイをトリガー
              uses: ttskch/render-deploy@v1.0.0
              with:
                  api-key: ${{ secrets.RENDER_API_KEY }}
                  service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
